Update new.yml

diff --git a/.github/workflows/new.yml b/.github/workflows/new.yml
--- a/.github/workflows/new.yml
+++ b/.github/workflows/new.yml
@@ -36,10 +36,11 @@ jobs:
         run: |
           docker exec ruby_appsec_web_1 rails tailwindcss:build
 
-      - name: Verify application is running
-        run: |
-          docker-compose ps -a
-          docker exec ruby_appsec_zap_1 curl --fail http://ruby_appsec_web_1:8880/users/sign_in || exit 1
+      
+      # - name: Verify application is running
+      #   run: |
+      #     docker-compose ps -a
+      #     docker exec ruby_appsec_zap_1 curl --fail http://ruby_appsec_web_1:8880/users/sign_in || exit 1
 
       - name: Seed Database (optional)
         run: |
@@ -48,6 +49,14 @@ jobs:
           docker exec ruby_appsec_db_1 psql -U postgres -d sql_injection_dev -c "SELECT * FROM users;"
         #  docker exec ruby_appsec_web_1 bash -c "rake db:seed"
 
+      - name: Run ZAP Baseline Scan (via Docker)
+        run: |
+          mkdir -p zap_reports
+          chmod 777 zap_reports
+          docker run --rm --network ruby_appsec_zapnet \
+            -v $(pwd)/zap_reports:/zap/wrk \
+            ghcr.io/zaproxy/zaproxy:stable \
+            zap-baseline.py -t http://ruby_appsec_web_1:8880/users/sign_in -J zap_report.json -d || true
       
       # - name: Run ZAP Docker
       #   run: |
